#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Introduction / Setup                                 #####
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Code for GSERM's "Regression for Publishing"
# (June 2024)
#
# Day One: Regression Overview & Review
#
# File last modified June 16, 2024
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Set working directory first:
#
# setwd("~/Dropbox (Personal)/GSERM/RFP2023/Slides") # or whatever...
#
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# This code takes a list of packages ("P") and (a) checks 
# for whether the package is installed or not, (b) installs 
# it if it is not, and then (c) loads each of them:

P<-c("readr","arm","car","psych","lmtest","plotrix","stargazer",
     "modelsummary","marginaleffects")

for (i in 1:length(P)) {
  ifelse(!require(P[i],character.only=TRUE),install.packages(P[i]),
         print(":)"))
  library(P[i],character.only=TRUE)
}
rm(P)
rm(i)

# Highlight that ^^^ block of code, then run it 7-8 times
# until you get all smileys. :)
#
# Next, set some R options:

options(scipen = 6) # bias against scientific notation
options(digits = 3) # show fewer decimal places

# We'll also read in a useful function that we'll use a 
# bit later:

url_std <- "http://www.stat.columbia.edu/~gelman/standardize/standardize.R"
eval(parse(text = getURL(url_std, ssl.verifypeer = FALSE)),
     envir=.GlobalEnv)
rm(url_std)

#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Regression, visually                        ####
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# We're going to be working with some cross-national
# data, where each observation in the data is a single
# country in the world. The spiurce of the data is 
# the "World Development Indicators" (also known
# as the "WDI"), which are data collected and 
# maintained primarily by the World bank and its
# partners. While the data exist for multiple years,
# we're going to focus on a single year, 2019 (the
# last more-or-less "normal" year before the COVID-19
# pandemic).
#
# 
# Read data from the github repo:

IR2018<-read.csv("https://github.com/PrisonRodeo/GSERM-RFP-2024/raw/main/Data/WDI-2018-Day-One-24.csv")

# Listwise delete data (this is not necessarily a
# good practice, but makes the plotting below easier,
# and in this case doesn't really harm the points I'm
# trying to make):

IR2018<-na.omit(IR2018)

#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Day One things for the slides...
#
# I offer no warranty that any of this is the most 
# efficient way to do what I'm doing... all graphics
# are using base R graphics functionality, with
# the exception of the scatterplot matrices, which use
# the -car- package, and the various plots generated by
# -modelsummary- and -marginaleffects-.

#=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Figure 1

pdf("IMbyLE-24.pdf",7,7) # make a PDF
par(cex=1.2) # make the things bigger
par(mar=c(4,4,2,2)) # plot margins
with(IR2018, plot(LifeExpectancy,InfantMortality, # draw the plot
                  pch="",xlab="Life Expectancy at Birth",
                  ylab="Infant Mortality Per 1000 Live Births"))
par(cex=0.8) # make the things smaller
# Add names:
with(IR2018, text(LifeExpectancy,InfantMortality,label=ISO3))
# add a linear-fit line
with(IR2018, abline(lm(InfantMortality~LifeExpectancy),lwd=3))
dev.off() # turn off the PDF-maker

#=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Figure 2 ("residual" plot)

IMLE.fit<-lm(InfantMortality~LifeExpectancy,data=IR2018)
IMLE.res<-resid(IMLE.fit)

pdf("IMbyLEresids-24.pdf",7,7) # make a PDF
par(cex=1.2)
par(mar=c(4,4,2,2))
plot(IR2018$LifeExpectancy,IMLE.res,pch="",
                  xlab="Life Expectancy at Birth",
                  ylab="Residuals (Observed minus Expected)")
par(cex=0.8)
text(IR2018$LifeExpectancy,IMLE.res,
                  label=IR2018$ISO3)
abline(h=0,lwd=3)
dev.off() # turn off the PDF-maker

#=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Figure 3

pdf("IMbyFertility-24.pdf",7,7) # make a PDF
par(mar=c(4,4,2,2)) # margins
par(cex=1.2) #symbol size
with(IR2018, plot(Fertility,InfantMortality,pch="",
                  xlab="Fertility Rate (Births Per Woman)",
                  ylab="Infant Mortality Per 1000 Live Births"))
par(cex=0.8)
with(IR2018, text(Fertility,InfantMortality,label=ISO3))
with(IR2018, abline(lm(InfantMortality~Fertility),lwd=3))
dev.off()

#=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Figure 4
#
# Make a lowess smoother:

GDPSmooth<-lowess(IR2018$GDPPerCapita,IR2018$InfantMortality,f=0.2) # lowess

# Plot:

pdf("IMbyGDP-24.pdf",7,7) # make a PDF
par(mar=c(4,4,2,2)) # margins
par(cex=1.2)
with(IR2018, plot(GDPPerCapita,InfantMortality,pch="",
                  xlab="Real GDP per capita",
                  ylab="Infant Mortality Per 1000 Live Births"))
par(cex=0.8)
with(IR2018, text(GDPPerCapita,InfantMortality,label=ISO3))
with(IR2018, abline(lm(InfantMortality~GDPPerCapita),lwd=3))
lines(GDPSmooth,lwd=3,col="red",lty=2)
par(cex=1)
legend("topright",bty="n",lwd=3,lty=c(1,2),col=c("black","red"),
       legend=c("Linear Fit","Lowess Fit"))
dev.off()

#=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Figure 5

pdf("lnIMbylnGDP-24.pdf",7,7) # make a PDF
par(mar=c(4,4,2,2)) # margins
par(cex=1.2)
with(IR2018, plot(log(GDPPerCapita),log(InfantMortality),pch="",
       xlab="Logged Real GDP per Capita",
       ylab="Logged Infant Mortality Per 1000 Live Births"))
par(cex=0.8)
with(IR2018, text(log(GDPPerCapita),log(InfantMortality),label=ISO3))
with(IR2018, abline(lm(log(InfantMortality)~log(GDPPerCapita)),lwd=3))
with(IR2018, lines(lowess(log(InfantMortality)~log(GDPPerCapita)),
                   lwd=3,lty=2,col="red"))
par(cex=1)
legend("topright",bty="n",lwd=3,lty=c(1,2),col=c("black","red"),
       legend=c("Linear Fit","Lowess Fit"))
dev.off()

#=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Figure 6

pdf("IMbyPOLITY-24.pdf",7,7) # make a PDF
par(mar=c(4,4,2,2)) # margins
par(cex=1.2)
with(IR2018, plot(POLITY,InfantMortality,pch="",
       xlab="POLITY V score",
       ylab="Infant Mortality Per 1000 Live Births"))
par(cex=0.8)
with(IR2018, text(POLITY,InfantMortality,label=ISO3))
with(IR2018, abline(lm(InfantMortality~POLITY),lwd=3))
with(IR2018, lines(lowess(InfantMortality~POLITY),lwd=3,
                   lty=2,col="red"))
par(cex=1)
legend("topleft",bty="n",lwd=3,lty=c(1,2),col=c("black","red"),
       legend=c("Linear Fit","Lowess Fit"))
dev.off()

#=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Figure 7:

IR2018$Rich<-as.factor(IR2018$GDPPerCapita>median(IR2018$GDPPerCapita,na.rm=TRUE))

pdf("IMbyPOLITYandGDP-24.pdf",7,7) # make a PDF
par(mar=c(4,4,2,2)) # margins
par(cex=1.2)
scatterplot(InfantMortality~POLITY|Rich,IR2018,cex=1.5,
            cex.axis=1.5,cex.lab=1.3,boxplots="",xlab="POLITY V", 
            ylab="Infant Mortality per 1000 Live Births",
            legend=list(coords="topleft",bty="n"),grid=FALSE,
            pch=c(16,17),regLine=FALSE,lwd=c(3,3),col=c(1,2),lty=c(3,4))
dev.off()

#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Multivariate Regression: Comceptual things...
#
# "Irrelevant" Z correlated with X but not with Y...
#
# Simulate *one* regression:

N<-50

set.seed(7222009)
X<-rnorm(N)         # Predictor
Z<-(X+rnorm(N))/1.5 # Z "caused by" X
Y<-X+rnorm(N)       # Outcome Y (unrelated to Z)

print(summary(lm(Y~X)))
print(summary(lm(Y~X+Z)))

# Do this 1000 times:

R<-1000
BX<-numeric(R)
BZ<-numeric(R)

set.seed(7222009)
for(i in 1:R){
  X<-rnorm(N)
  Z<-(X+rnorm(N))/1.5
  Y<-X+rnorm(N)
  f<-lm(Y~X+Z)
  BX[i]<-coef(f)[2]
  BZ[i]<-coef(f)[3]
}

# Plot:

pdf("IrrPredictor.pdf",7,6)
par(mar=c(4,4,2,2))
plot(density(BX),xlim=c(-1.2,2.2),lwd=2,
     xlab="Estimates of Beta",main="")
lines(density(BZ),lwd=2,lty=2,col="orange")
abline(v=1,lty=2,col="grey")
abline(v=0,lty=2,col="orange")
legend("topright",lwd=2,lty=c(1,2),col=c("black","orange","white"),
       bty="n",legend=c("Predictor","Irrelevant Z"," (N=50)"))
dev.off()

# Make N 10x larger...

N<-500
R<-1000
BX<-numeric(R)
BZ<-numeric(R)

set.seed(7222009)
for(i in 1:R){
  X<-rnorm(N)
  Z<-(X+rnorm(N))/1.5
  Y<-X+rnorm(N)
  f<-lm(Y~X+Z)
  BX[i]<-coef(f)[2]
  BZ[i]<-coef(f)[3]
}

# Plot:

pdf("IrrPredictor2.pdf",7,6)
par(mar=c(4,4,2,2))
plot(density(BX),xlim=c(-1.2,2.2),lwd=2,
     xlab="Estimates of Beta",main="")
lines(density(BZ),lwd=2,lty=2,col="orange")
abline(v=1,lty=2,col="grey")
abline(v=0,lty=2,col="orange")
legend("topright",lwd=2,lty=c(1,2),col=c("black","orange","white"),
       bty="n",legend=c("Predictor","Irrelevant Z"," (N=500)"))
dev.off()

# Next, a Z that is correlated with Y but not with X...

N<-50

set.seed(7222009)
X<-rnorm(N)         # Predictor
Z<-rnorm(N)         # Z orthogonal to X
Y<-X+Z+rnorm(N)     # Outcome Y 

print(summary(lm(Y~X)))
print(summary(lm(Y~X+Z)))

# Now some sims:

N<-50
R<-1000
BX<-numeric(R)
BZ<-numeric(R)
BX0<-numeric(R)

set.seed(7222009)
for(i in 1:R){
  X<-rnorm(N)
  Z<-rnorm(N)
  Y<-X+Z+rnorm(N)
  f1<-lm(Y~X)
  f2<-lm(Y~X+Z)
  BX0[i]<-coef(f1)[2]  
  BX[i]<-coef(f2)[2]
  BZ[i]<-coef(f2)[3]
}

# Plot:

pdf("UncorrPredictors.pdf",7,6)
par(mar=c(4,4,2,2))
plot(density(BX),xlim=c(0,2),lwd=2,ylim=c(0,3),
     xlab="Estimates of Beta",main="")
lines(density(BZ),lwd=2,lty=2,col="orange")
lines(density(BX0),lwd=2,lty=3,col="navy")
abline(v=1,lty=2,col="grey")
legend("topright",lwd=2,lty=c(1,2,3),bty="n",
       col=c("black","orange","navy","white"),
       legend=c("Predictor","Z","Predictor w/o Z","   (N=50)"))
dev.off()

# Increase N to 500, same...

N<-500
R<-1000
BX<-numeric(R)
BZ<-numeric(R)
BX0<-numeric(R)

set.seed(7222009)
for(i in 1:R){
  X<-rnorm(N)
  Z<-rnorm(N)
  Y<-X+Z+rnorm(N)
  f1<-lm(Y~X)
  f2<-lm(Y~X+Z)
  BX0[i]<-coef(f1)[2]  
  BX[i]<-coef(f2)[2]
  BZ[i]<-coef(f2)[3]
}

# Plot:

pdf("UncorrPredictors2.pdf",7,6)
par(mar=c(4,4,2,2))
plot(density(BX),xlim=c(0,2),lwd=2,ylim=c(0,10),
     xlab="Estimates of Beta",main="")
lines(density(BZ),lwd=2,lty=2,col="orange")
lines(density(BX0),lwd=2,lty=3,col="navy")
abline(v=1,lty=2,col="grey")
legend("topright",lwd=2,lty=c(1,2,3),bty="n",
       col=c("black","orange","navy","white"),
       legend=c("Predictor","Z","Predictor w/o Z","   (N=500)"))
dev.off()

# Next: Z is a confounder...

N<-50
R<-1000
BX<-numeric(R)
BZ<-numeric(R)
BX0<-numeric(R)

set.seed(7222009)
for(i in 1:R){
  Z<-rnorm(N)
  X<-(Z+rnorm(N))/1.5
  Y<-X+Z+rnorm(N)
  f1<-lm(Y~X)
  f2<-lm(Y~X+Z)
  BX0[i]<-coef(f1)[2]  
  BX[i]<-coef(f2)[2]
  BZ[i]<-coef(f2)[3]
}

# Plot:

pdf("Confounder.pdf",7,6)
par(mar=c(4,4,2,2))
plot(density(BX),xlim=c(0,2.5),lwd=2,ylim=c(0,2.5),
     xlab="Estimates of Beta",main="")
lines(density(BZ),lwd=2,lty=2,col="orange")
lines(density(BX0),lwd=2,lty=3,col="navy")
abline(v=1,lty=2,col="grey")
legend("topleft",lwd=2,lty=c(1,2,3),bty="n",
       col=c("black","orange","navy","white"),
       legend=c("Predictor","Confounder Z","Predictor w/o Z","  (N=50)"))
dev.off()

# Same with N=500:

N<-500
R<-1000
BX<-numeric(R)
BZ<-numeric(R)
BX0<-numeric(R)

set.seed(7222009)
for(i in 1:R){
  Z<-rnorm(N)
  X<-(Z+rnorm(N))/1.5
  Y<-X+Z+rnorm(N)
  f1<-lm(Y~X)
  f2<-lm(Y~X+Z)
  BX0[i]<-coef(f1)[2]  
  BX[i]<-coef(f2)[2]
  BZ[i]<-coef(f2)[3]
}

# Plot:

pdf("Confounder2.pdf",7,6)
par(mar=c(4,4,2,2))
plot(density(BX),xlim=c(0,2.5),lwd=2,ylim=c(0,7),
     xlab="Estimates of Beta",main="")
lines(density(BZ),lwd=2,lty=2,col="orange")
lines(density(BX0),lwd=2,lty=3,col="navy")
abline(v=1,lty=2,col="grey")
legend("topleft",lwd=2,lty=c(1,2,3),bty="n",
       col=c("black","orange","navy","white"),
       legend=c("Predictor","Confounder Z","Predictor w/o Z","  (N=500)"))
dev.off()

# Now, a collider:

N<-50
R<-1000
BX<-numeric(R)
BZ<-numeric(R)
BX0<-numeric(R)

set.seed(7222009)
for(i in 1:R){
  X<-rnorm(N)
  Y<-X+rnorm(N)
  Z<-(X+Y+rnorm(N))/1.5
  f1<-lm(Y~X)
  f2<-lm(Y~X+Z)
  BX0[i]<-coef(f1)[2]  
  BX[i]<-coef(f2)[2]
  BZ[i]<-coef(f2)[3]
}

# Plot:

pdf("Collider.pdf",7,6)
par(mar=c(4,4,2,2))
plot(density(BX0),xlim=c(-1,2),lwd=2,ylim=c(0,4),
     xlab="Estimates of Beta",main="")
lines(density(BZ),lwd=2,lty=2,col="orange")
lines(density(BX),lwd=2,lty=3,col="navy")
abline(v=1,lty=2,col="grey")
legend("topleft",lwd=2,lty=c(1,2,3),bty="n",
       col=c("black","orange","navy","white"),
       legend=c("Predictor","Collider Z","Predictor w/Z","  (N=50)"))
dev.off()

# Same w / N=500:

N<-500
R<-1000
BX<-numeric(R)
BZ<-numeric(R)
BX0<-numeric(R)

set.seed(7222009)
for(i in 1:R){
  X<-rnorm(N)
  Y<-X+rnorm(N)
  Z<-(X+Y+rnorm(N))/1.5
  f1<-lm(Y~X)
  f2<-lm(Y~X+Z)
  BX0[i]<-coef(f1)[2]  
  BX[i]<-coef(f2)[2]
  BZ[i]<-coef(f2)[3]
}

# Plot:

pdf("Collider2.pdf",7,6)
par(mar=c(4,4,2,2))
plot(density(BX0),xlim=c(-1,2),lwd=2,ylim=c(0,11),
     xlab="Estimates of Beta",main="")
lines(density(BZ),lwd=2,lty=2,col="orange")
lines(density(BX),lwd=2,lty=3,col="navy")
abline(v=1,lty=2,col="grey")
legend("topleft",lwd=2,lty=c(1,2,3),bty="n",
       col=c("black","orange","navy","white"),
       legend=c("Predictor","Collider Z","Predictor w/Z","  (N=500)"))
dev.off()

# Last: Mediators!

N<-50
R<-1000
BX<-numeric(R)
BZ<-numeric(R)
BX0<-numeric(R)

set.seed(7222009)
for(i in 1:R){
  X<-rnorm(N)
  Z<-X+rnorm(N) / 1.6 # Z influenced by X
  Y<-(X+Z+rnorm(N))   # Y = f(X,Z)
  f1<-lm(Y~X)         # No Z ("total" X effect)
  f2<-lm(Y~X+Z)       # With Z ("direct" X effect)
  BX0[i]<-coef(f1)[2]  
  BX[i]<-coef(f2)[2]
  BZ[i]<-coef(f2)[3]
}

# Plot:

pdf("Mediator.pdf",7,6)
par(mar=c(4,4,2,2))
plot(density(BX),xlim=c(-0.5,3),lwd=2,ylim=c(0,3),
     xlab="Estimates of Beta",main="")
lines(density(BZ),lwd=2,lty=2,col="orange")
lines(density(BX0),lwd=2,lty=3,col="navy")
abline(v=1,lty=2,col="grey")
legend("topleft",lwd=2,lty=c(1,2,3),bty="n",
       col=c("black","orange","navy","white"),
       legend=c("Predictor","Mediator Z","Predictor w/o Z","  (N=50)"))
dev.off()

# Now with N=500:

N<-500
R<-1000
BX<-numeric(R)
BZ<-numeric(R)
BX0<-numeric(R)

set.seed(7222009)
for(i in 1:R){
  X<-rnorm(N)
  Z<-X+rnorm(N) / 1.6 # Z influenced by X
  Y<-(X+Z+rnorm(N))   # Y = f(X,Z)
  f1<-lm(Y~X)         # No Z ("total" X effect)
  f2<-lm(Y~X+Z)       # With Z ("direct" X effect)
  BX0[i]<-coef(f1)[2]  
  BX[i]<-coef(f2)[2]
  BZ[i]<-coef(f2)[3]
}

# Plot:

pdf("Mediator2.pdf",7,6)
par(mar=c(4,4,2,2))
plot(density(BX),xlim=c(-0.5,3),lwd=2,ylim=c(0,8.5),
     xlab="Estimates of Beta",main="")
lines(density(BZ),lwd=2,lty=2,col="orange")
lines(density(BX0),lwd=2,lty=3,col="navy")
abline(v=1,lty=2,col="grey")
legend("topleft",lwd=2,lty=c(1,2,3),bty="n",
       col=c("black","orange","navy","white"),
       legend=c("Predictor","Mediator Z","Predictor w/o Z","  (N=500)"))
dev.off()


#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# IM / DPT Bivariate Regression Example             ####
#
# Recode missingness in two variables:

IR2018$DemocScore<-ifelse(IR2018$DemocScore==-77,0,IR2018$DemocScore)
IR2018$AutocScore<-ifelse(IR2018$AutocScore==-77,0,IR2018$AutocScore)

# WDI Data summary:

describe(IR2018)

cor(IR2018[,3:9],,use="complete.obs")

# Scatterplot matrix:
# 
# df<-IR2018[,3:9]
# 
# pdf("ChildMortScatterMatrix-24.pdf",7,6)
# par(mar=c(2,2,2,2))
# scatterplotMatrix(df,col="black",pch=20)
# dev.off()

# Regression:

IMDPT<-lm(InfantMortality~DPTPercent,data=IR2018)
summary.lm(IMDPT)

# ANOVA

anova(IMDPT)

# Scatterplot:

pdf("IMDPT-24.pdf",6,6) # <- create PDF
with(IR2018, plot(DPTPercent,InfantMortality,pch=".",
                xlab="DPT Immunization Percentage",
                ylab="Infant Mortality (Deaths per 1000 Births)"))
par(cex=0.8)
with(IR2018, text(DPTPercent,InfantMortality,labels=ISO3))
with(IR2018, abline(v=mean(DPTPercent,na.rm=TRUE),lty=2))
with(IR2018, abline(h=mean(InfantMortality,na.rm=TRUE),lty=2))
abline(IMDPT,lwd=3)
dev.off()

# Residuals (u):

IR2018$IMDPTres <- with(IR2018, residuals(IMDPT))
describe(IR2018$IMDPTres)

# Residual density plot:

pdf("IMDPTResidualsDensity-24.pdf",6,6)
with(IR2018, plot(density(IMDPTres,na.rm=TRUE),
                main="Density Plot: Regression Residuals",
                xlab="Residual Value"))
abline(v=0,lty=2,lwd=2)
dev.off()

# Fitted Values:

IR2018$IMDPThat<-fitted.values(IMDPT)
describe(IR2018$IMDPThat)

# Densities plot:

pdf("IMDPTFittedDensity-24.pdf",6,6)
with(IR2018, plot(density(IMDPThat,na.rm=TRUE),lwd=2,
                main="Density Plot: Actual and Fitted Values",
                xlab="Values of Y"))
with(IR2018, lines(density(InfantMortality,na.rm=TRUE),
                 lty=2,col="red",lwd=2))
with(IR2018, abline(v=mean(InfantMortality,na.rm=TRUE),
                  lty=2,lwd=2))
legend("topright",bty="n",lty=c(1,2),lwd=2,col=c("black","red"),
       legend=c("Actual Values","Fitted Values"))
dev.off()

# Correlations:
# 
# with(IR2018, cor(InfantMortality,DPTPercent,use="complete.obs"))
# with(IR2018, cor(IMDPTres,InfantMortality,use="complete.obs"))
# with(IR2018, cor(IMDPTres,DPTPercent,use="complete.obs"))
# with(IR2018, cor(IMDPThat,InfantMortality,use="complete.obs"))
# with(IR2018, cor(IMDPThat,DPTPercent,use="complete.obs"))
# with(IR2018, cor(IMDPTres,IMDPThat,use="complete.obs"))

# Plotting residuals vs. X:

pdf("IMDPTResiduals-24.pdf",6,6)
with(IR2018, plot(DPTPercent,IMDPTres,pch=".",
                xlab="DPT Immunization Percentage",
                ylab="Residuals (Y - Y-hat)"))
with(IR2018, text(DPTPercent,IMDPTres,labels=ISO3,cex=0.6))
abline(h=0,lwd=2)
dev.off()

# Squared residuals vs. X:

pdf("IMDPTSquaredResiduals-24.pdf",6,6)
with(IR2018, plot(DPTPercent,IMDPTres^2,pch=".",
                xlab="DPT Immunization Percentage",
                ylab="Residuals (Y - Y-hat)"))
with(IR2018, text(DPTPercent,IMDPTres^2,labels=ISO3,cex=0.6))
dev.off() 

# Inference...
#
# Var-Cov matrix of estimated betas:

vcov(IMDPT)

# Confidence intervals (here, 95 percent):

confint(IMDPT)

# Predictions:

SEs<-predict(IMDPT,interval="confidence")
SEs

# Plot it!:

Sort<-order(IR2018$DPTPercent)

pdf("IMDPT-CI-24.pdf",6,5)
par(mar=c(4,4,1,2))
plot(IR2018$DPTPercent,IR2018$InfantMortality,pch=20,
     xlab="DPT Immunization Percentage",
     ylab="Infant Mortality Per 1000 Births")
abline(IMDPT,lwd=3)
lines(sort(IR2018$DPTPercent),SEs[Sort,2],col="red",lwd=2,lty=2)
lines(sort(IR2018$DPTPercent),SEs[Sort,3],col="red",lwd=2,lty=2)
dev.off()


#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Multivariate Regression example                     ####
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

# Multivariate regression of Infant Mortality on several 
# potentially-relevant variables:

model<-lm(InfantMortality~DPTPercent+GDPPerCapita+FDIIn+
          NaturalResourceRents+UrbanPopulation+GovtExpenditures+
          POLITY+PaidParentalLeave,data=IR2018)
summary(model)

# Variance-Covariance matrix of betas:

vcov(model)

# F-tests...
#
# FDI In = POLITY = 0:

modelsmall<-lm(InfantMortality~DPTPercent+GDPPerCapita+NaturalResourceRents+
                      UrbanPopulation+GovtExpenditures+PaidParentalLeave,
                      data=IR2018)
waldtest(model,modelsmall)  # from -lmtest- package

# NaturalResourceRents=1.0:

linearHypothesis(model,"NaturalResourceRents=1") # from -car-

# NaturalResourceRents = -UrbanPopulation:

linearHypothesis(model,"NaturalResourceRents = -UrbanPopulation")

# Reporting: the output:

summary(model)

# Reporting: The table:

stargazer(model,
          type="latex",
          title="OLS Regression Model of Child Mortality Rates, 2018",
          dep.var.caption="",
          dep.var.labels="Model I",
          digits=2,
          no.space=TRUE,
          intercept.top=TRUE,intercept.bottom=FALSE,
          covariate.labels=c("(Constant)",
                             "DPT Immunization Rate",
                             "GDP Per Capita",
                             "Inward FDI",
                             "Natural Resource Rents (Pct. GDP)",
                             "Urban Population (Pct.)",
                             "Government Expenditures (Pct. GDP)",
                             "POLITY V (Democracy) Score",
                             "Paid Parental Leave"))

# Multiple models:

modelsmol<-lm(InfantMortality~DPTPercent,data=IR2018)

stargazer(modelsmol,model,modelsmall,
          type="latex",
          title="OLS Regression Models of Infant Mortality Rates, 2018",
          dep.var.caption="",
          column.labels=c("Univariate","Full","Reduced"),
          digits=2,
          no.space=TRUE,
          intercept.top=TRUE,intercept.bottom=FALSE,
          covariate.labels=c("(Constant)",
                             "DPT Immunization Rate",
                             "GDP Per Capita",
                             "Inward FDI",
                             "Natural Resource Rents (Pct. GDP)",
                             "Urban Population (Pct.)",
                             "Government Expenditures (Pct. GDP)",
                             "POLITY V (Democracy) Score",
                             "Paid Parental Leave"))

# Note that the -texreg- and -modelsummary- packages
# will also make nice tables for Word, LaTeX, etc.
#
# Replacing tables with figures... we can use the
# -modelplot- command in the -modelsummary- package
# for this... 
#
# Basic / first model:

pdf("OLS-Ladder-I-24.pdf",6,4)
par(mar=c(4,4,2,2))
modelplot(model)
dev.off()

# Ouch; rescale the predictors...

modelS<-standardize(model)
summary(modelS)

# Redraw the plot:

pdf("OLS-Ladder-II-24.pdf",6,4)
par(mar=c(4,4,2,2))
modelplot(modelS,
          coef_rename=c("z.DPTPercent"="DPT Percent",
                        "z.GDPPerCapita"="GDP Per Capita",
                        "z.FDIIn"="Inward FDI",
                        "z.NaturalResourceRents"="Natural Resource Rents",
                        "z.UrbanPopulation"="Urban Population",
                        "z.GovtExpenditures"="Government Expenditures",
                        "z.POLITY"="POLITY",
                        "c.PaidParentalLeave"="Paid Parental Leave"))
dev.off()


# We can also do this for multiple models at once. To
# do that using -modelsummary-, we re-fit our models:

modelSB<-standardize(modelsmol)  # bivariate
modelSF<-standardize(model)      # full
modelSR<-standardize(modelsmall) # reduced 

# ...then make a list of them:

models<-list("Bivariate"=modelSB,
             "Full"=modelSF,
             "Reduced"=modelSR)

# Plot:

pdf("OLS-Ladder-III-24.pdf",8,4)
modelplot(models,
          coef_rename=c("z.DPTPercent"="DPT Percent",
                        "z.GDPPerCapita"="GDP Per Capita",
                        "z.FDIIn"="Inward FDI",
                        "z.NaturalResourceRents"="Natural Resource Rents",
                        "z.UrbanPopulation"="Urban Population",
                        "z.GovtExpenditures"="Government Expenditures",
                        "z.POLITY"="POLITY",
                        "c.PaidParentalLeave"="Paid Parental Leave"))
dev.off()

# /fin